er_user:
    resource: "@ERUserBundle/Resources/config/routing.yml"
    prefix:   /

er_boxshadow:
    resource: "@ERBoxShadowBundle/Resources/config/routing.yml"
    prefix:   /box-shadow

security_login:
    path: /login
    defaults:
        _controller: ERUserBundle:Security:login

security_register:
    path: /register
    defaults:
         _controller: ERUserBundle:Security:register

security_logout:
    path: /logout
