er_user:
    resource: "@ERUserBundle/Resources/config/routing.yml"
    prefix:   /

er_boxshadow:
    resource: "@ERBoxShadowBundle/Resources/config/routing.yml"
    prefix:   /box-shadow

login:
    path: /login
    defaults:
        _controller: ERUserBundle:Security:login

login_check:
    path: /login_check
    defaults:
         _controller: ERUserBundle:Security:loginCheck

register:
    path: /register
    defaults:
         _controller: ERUserBundle:Security:register

logout:
    path: /logout
