# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ER\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:    [ ROLE_AUTEUR, ROLE_MODERATEUR ]
        ROLE_SUPER_ADMIN:    [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:    ER\UserBundle\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:     ^/(_(profiler|wdt)|css|images|js)/
            security:    false
        main_login:
            pattern:     ^/login$
            anonymous:   true
        main_console:
            pattern:     ^/_console
            anonymous:   true
        main:
            pattern:     ^/
            anonymous:   false
            provider:    main
            form_login:
                login_path:  /login
                check_path:  login_check
                default_target_path: er_boxshadow_home
            logout:
                path:    /logout
                target:  login

    access_control:
        #- { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
