# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        ER\UserBundle\Entity\User:
            algorithm:  bcrypt
            cost:  12

    role_hierarchy:
        ROLE_ADMIN:    [ ROLE_AUTEUR, ROLE_MODERATEUR, ROLE_USER ]
        ROLE_SUPER_ADMIN:    [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_USER ]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:    ER\UserBundle\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:     ^/(_(profiler|wdt)|css|images|js)/
            security:    false
        main:
            pattern:     ^/
            anonymous:   ~
            provider:    main
            form_login:
                login_path:  security_login
                check_path:  security_login
                default_target_path: er_boxshadow_home
            logout:
                path:    security_logout
                target:  security_login

    access_control:
        - { path: ^/_console,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/box-shadow, roles: ROLE_USER }
