parameters:
    name:  rachid

services:
    er_boxshadow_antispam:
        class: ER\BoxShadowBundle\Antispam\ERAntispam
        arguments:
            - '@mailer'
            - '%locale%'
            - 50
