parameters:
    name:  rachid

services:
    er_boxshadow_antispam:
        class: ER\BoxShadowBundle\Antispam\ERAntispam
        arguments:
            - '@mailer'
            - '%locale%'
            - 50

    er_boxshadow.email.application_mailer:
        class: ER\BoxShadowBundle\Email\ApplicationMailer
        arguments:
            - '@mailer'

    er_boxshadow.doctrine_listener.application_creation_listener:
        class: ER\BoxShadowBundle\DoctrineListener\ApplicationCreationListener
        arguments:
          - '@er_boxshadow.email.application_mailer'
        tags:
          - { name: doctrine.event_listener, event: postPersist }

    er_boxshadow.validator.antiflood:
        class: ER\BoxShadowBundle\Validator\AntiFloodValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
          - { name: validator.constraint_validator, alias: er_boxshadow_antiflood}

