services:
    er_boxshadow_antispam:
        class: ER\BoxShadowBundle\Antispam\ERAntispam
        arguments:
            - '@mailer'
            - '%locale%'
        calls:
            - [ setLocale, [%locale%]]

    er_platform.twig.antispam_extension:
        class: ER\BoxShadowBundle\Antispam\AntiSpamExtension
        arguments:
            - '@er_boxshadow_antispam'
        tags:
            - { name: twig.extension }

    er_boxshadow.email.application_mailer:
        class: ER\BoxShadowBundle\Email\ApplicationMailer
        arguments:
            - '@mailer'

    er_boxshadow.doctrine_listener.application_creation_listener:
        class: ER\BoxShadowBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - '@er_boxshadow.email.application_mailer'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    er_boxshadow.validator.antiflood:
        class: ER\BoxShadowBundle\Validator\AntiFloodValidator
        arguments: [ '@request_stack', '@doctrine.orm.entity_manager' ]
        tags:
            - { name: validator.constraint_validator, alias: er_boxshadow_antiflood }

    er_boxshadow.form.ckeditor:
        class: ER\BoxShadowBundle\Form\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }

    er_boxshadow.beta.html_adder:
        class: ER\BoxShadowBundle\Beta\BetaHTMLAdder

    er_boxshadow.listener.beta:
        class: ER\BoxShadowBundle\Listener\BetaListener
        arguments:
            - '@er_boxshadow.beta.html_adder'
            - '2017-06-01'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

